# Generated by Django 3.2.5 on 2021-08-07 16:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoProducts',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('base_currency', models.CharField(max_length=100)),
                ('quote_currency', models.CharField(max_length=100)),
                ('base_increment', models.CharField(max_length=100)),
                ('quote_increment', models.CharField(max_length=100)),
                ('base_min_size', models.CharField(max_length=100)),
                ('base_max_size', models.CharField(max_length=100)),
                ('min_market_funds', models.CharField(max_length=100)),
                ('max_market_funds', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('status_message', models.CharField(blank=True, max_length=1000)),
                ('cancel_only', models.BooleanField(default=False)),
                ('limit_only', models.BooleanField(default=False)),
                ('post_only', models.BooleanField(default=False)),
                ('trading_disabled', models.BooleanField(default=False)),
                ('fx_stablecoin', models.BooleanField(default=False)),
                ('margin_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['base_currency'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_currency', models.CharField(choices=[('GBP', 'British Pounds'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=10, validators=[django.core.validators.MaxValueValidator(Decimal('35000')), django.core.validators.MinValueValidator(Decimal('10'))])),
                ('crypto_product', models.CharField(choices=[('USDT', 'USDT'), ('NKN', 'NKN'), ('BOND', 'BOND'), ('MASK', 'MASK'), ('CTSI', 'CTSI'), ('OXT', 'OXT'), ('AMP', 'AMP'), ('FIL', 'FIL'), ('SNX', 'SNX'), ('YFI', 'YFI'), ('TRB', 'TRB'), ('FORTH', 'FORTH'), ('AAVE', 'AAVE'), ('ADA', 'ADA'), ('LPT', 'LPT'), ('DASH', 'DASH'), ('RAI', 'RAI'), ('DOT', 'DOT'), ('ZRX', 'ZRX'), ('KEEP', 'KEEP'), ('REP', 'REP'), ('FET', 'FET'), ('WBTC', 'WBTC'), ('ATOM', 'ATOM'), ('MLN', 'MLN'), ('ENJ', 'ENJ'), ('SOL', 'SOL'), ('BAT', 'BAT'), ('EOS', 'EOS'), ('XLM', 'XLM'), ('NU', 'NU'), ('ETC', 'ETC'), ('MIR', 'MIR'), ('STORJ', 'STORJ'), ('KNC', 'KNC'), ('QNT', 'QNT'), ('LRC', 'LRC'), ('PLA', 'PLA'), ('MKR', 'MKR'), ('REN', 'REN'), ('BAL', 'BAL'), ('ACH', 'ACH'), ('LTC', 'LTC'), ('POLY', 'POLY'), ('CGLD', 'CGLD'), ('XTZ', 'XTZ'), ('ANKR', 'ANKR'), ('SKL', 'SKL'), ('MATIC', 'MATIC'), ('BAND', 'BAND'), ('CHZ', 'CHZ'), ('GTC', 'GTC'), ('CLV', 'CLV'), ('RLY', 'RLY'), ('ETH', 'ETH'), ('UNI', 'UNI'), ('BNT', 'BNT'), ('BCH', 'BCH'), ('1INCH', '1INCH'), ('UMA', 'UMA'), ('SUSHI', 'SUSHI'), ('BTC', 'BTC'), ('OMG', 'OMG'), ('ALGO', 'ALGO'), ('DOGE', 'DOGE'), ('PAX', 'PAX'), ('FARM', 'FARM'), ('LINK', 'LINK'), ('NMR', 'NMR'), ('ZEC', 'ZEC'), ('ICP', 'ICP'), ('CRV', 'CRV'), ('DAI', 'DAI'), ('GRT', 'GRT'), ('RLC', 'RLC'), ('MANA', 'MANA'), ('COMP', 'COMP'), ('OGN', 'OGN')], max_length=30)),
                ('order_type', models.CharField(choices=[('limit', 'Limit'), ('market', 'Market')], default='market', max_length=30)),
                ('execution_frequency', models.CharField(choices=[('bimo', 'BiMonthly'), ('mo', 'Monthly'), ('wk', 'Weekly'), ('day', 'Daily')], default='day', max_length=100)),
                ('execution_count', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_execution_date', models.DateTimeField(blank=True, null=True)),
                ('next_execution_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('execution_needed', models.BooleanField(default=False)),
                ('has_error', models.BooleanField(default=False)),
                ('error_desc', models.CharField(blank=True, default='', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_execution_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_pro', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coinbase_id', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_date', models.CharField(blank=True, max_length=100, null=True)),
                ('is_settled', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=200)),
                ('fulfilled_date', models.CharField(blank=True, max_length=100, null=True)),
                ('order_type', models.CharField(default='market', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('product_id', models.CharField(blank=True, max_length=15, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True)),
                ('executed_value', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DCAstrategies.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('API_secret', models.CharField(max_length=100)),
                ('API_key', models.CharField(max_length=100)),
                ('passphrase', models.CharField(max_length=100)),
                ('scope', models.CharField(default='View; Transfer; Trade;', max_length=100)),
                ('preferred_payment_method_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('preferred_payment_method_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
