# Generated by Django 3.2.5 on 2021-08-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('OXT', 'OXT'), ('ETH', 'ETH'), ('BAL', 'BAL'), ('CLV', 'CLV'), ('PLA', 'PLA'), ('CTSI', 'CTSI'), ('GTC', 'GTC'), ('CGLD', 'CGLD'), ('ALGO', 'ALGO'), ('DASH', 'DASH'), ('ETC', 'ETC'), ('AAVE', 'AAVE'), ('FIL', 'FIL'), ('BNT', 'BNT'), ('XLM', 'XLM'), ('NMR', 'NMR'), ('MANA', 'MANA'), ('YFI', 'YFI'), ('OMG', 'OMG'), ('LPT', 'LPT'), ('EOS', 'EOS'), ('REN', 'REN'), ('WBTC', 'WBTC'), ('BCH', 'BCH'), ('BAT', 'BAT'), ('USDT', 'USDT'), ('ACH', 'ACH'), ('MKR', 'MKR'), ('REP', 'REP'), ('SUSHI', 'SUSHI'), ('ANKR', 'ANKR'), ('MLN', 'MLN'), ('1INCH', '1INCH'), ('FARM', 'FARM'), ('DAI', 'DAI'), ('RLY', 'RLY'), ('BAND', 'BAND'), ('LINK', 'LINK'), ('TRB', 'TRB'), ('BTC', 'BTC'), ('COMP', 'COMP'), ('POLY', 'POLY'), ('SNX', 'SNX'), ('NU', 'NU'), ('MIR', 'MIR'), ('OGN', 'OGN'), ('MASK', 'MASK'), ('ADA', 'ADA'), ('GRT', 'GRT'), ('PAX', 'PAX'), ('KEEP', 'KEEP'), ('ZEC', 'ZEC'), ('STORJ', 'STORJ'), ('KNC', 'KNC'), ('NKN', 'NKN'), ('ENJ', 'ENJ'), ('ATOM', 'ATOM'), ('SKL', 'SKL'), ('SOL', 'SOL'), ('FORTH', 'FORTH'), ('RLC', 'RLC'), ('FET', 'FET'), ('CRV', 'CRV'), ('ICP', 'ICP'), ('AMP', 'AMP'), ('UNI', 'UNI'), ('LRC', 'LRC'), ('RAI', 'RAI'), ('QNT', 'QNT'), ('BOND', 'BOND'), ('DOGE', 'DOGE'), ('ZRX', 'ZRX'), ('MATIC', 'MATIC'), ('CHZ', 'CHZ'), ('UMA', 'UMA'), ('XTZ', 'XTZ'), ('DOT', 'DOT'), ('LTC', 'LTC')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('bimo', 'BiMonthly'), ('day', 'Daily'), ('wk', 'Weekly'), ('mo', 'Monthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='order_type',
            field=models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], default='market', max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('GBP', 'British Pounds'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='USD', max_length=3),
        ),
    ]
