# Generated by Django 3.2.5 on 2021-08-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0003_auto_20210807_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('NMR', 'NMR'), ('COMP', 'COMP'), ('LTC', 'LTC'), ('FIL', 'FIL'), ('ETH', 'ETH'), ('AAVE', 'AAVE'), ('QNT', 'QNT'), ('PLA', 'PLA'), ('PAX', 'PAX'), ('ZEC', 'ZEC'), ('GTC', 'GTC'), ('MANA', 'MANA'), ('MATIC', 'MATIC'), ('NU', 'NU'), ('UNI', 'UNI'), ('ATOM', 'ATOM'), ('SNX', 'SNX'), ('LPT', 'LPT'), ('ZRX', 'ZRX'), ('CRV', 'CRV'), ('YFI', 'YFI'), ('BAL', 'BAL'), ('OGN', 'OGN'), ('KEEP', 'KEEP'), ('AMP', 'AMP'), ('UMA', 'UMA'), ('CHZ', 'CHZ'), ('BAND', 'BAND'), ('BCH', 'BCH'), ('CGLD', 'CGLD'), ('DAI', 'DAI'), ('OXT', 'OXT'), ('XTZ', 'XTZ'), ('GRT', 'GRT'), ('CTSI', 'CTSI'), ('BOND', 'BOND'), ('ETC', 'ETC'), ('MKR', 'MKR'), ('1INCH', '1INCH'), ('USDT', 'USDT'), ('SUSHI', 'SUSHI'), ('STORJ', 'STORJ'), ('BAT', 'BAT'), ('MLN', 'MLN'), ('ICP', 'ICP'), ('ENJ', 'ENJ'), ('RLY', 'RLY'), ('DASH', 'DASH'), ('MASK', 'MASK'), ('NKN', 'NKN'), ('EOS', 'EOS'), ('ANKR', 'ANKR'), ('BTC', 'BTC'), ('ALGO', 'ALGO'), ('LINK', 'LINK'), ('ADA', 'ADA'), ('FORTH', 'FORTH'), ('XLM', 'XLM'), ('REP', 'REP'), ('FARM', 'FARM'), ('BNT', 'BNT'), ('LRC', 'LRC'), ('POLY', 'POLY'), ('TRB', 'TRB'), ('FET', 'FET'), ('SKL', 'SKL'), ('ACH', 'ACH'), ('MIR', 'MIR'), ('REN', 'REN'), ('RAI', 'RAI'), ('KNC', 'KNC'), ('WBTC', 'WBTC'), ('OMG', 'OMG'), ('DOT', 'DOT'), ('SOL', 'SOL'), ('CLV', 'CLV'), ('DOGE', 'DOGE'), ('RLC', 'RLC')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('bimo', 'BiMonthly'), ('wk', 'Weekly'), ('day', 'Daily'), ('mo', 'Monthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('USD', 'US Dollars'), ('GBP', 'British Pounds')], default='USD', max_length=3),
        ),
    ]
