# Generated by Django 3.2.5 on 2021-08-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0004_auto_20210807_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='fees_saved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='still_exists',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('GTC', 'GTC'), ('PLA', 'PLA'), ('TRB', 'TRB'), ('DAI', 'DAI'), ('POLY', 'POLY'), ('CGLD', 'CGLD'), ('AMP', 'AMP'), ('BCH', 'BCH'), ('NMR', 'NMR'), ('ADA', 'ADA'), ('SNX', 'SNX'), ('QNT', 'QNT'), ('PAX', 'PAX'), ('KNC', 'KNC'), ('XTZ', 'XTZ'), ('DOGE', 'DOGE'), ('MIR', 'MIR'), ('ATOM', 'ATOM'), ('FET', 'FET'), ('DOT', 'DOT'), ('SUSHI', 'SUSHI'), ('OXT', 'OXT'), ('YFI', 'YFI'), ('BAL', 'BAL'), ('MKR', 'MKR'), ('ANKR', 'ANKR'), ('1INCH', '1INCH'), ('COMP', 'COMP'), ('ENJ', 'ENJ'), ('ZEC', 'ZEC'), ('OGN', 'OGN'), ('USDT', 'USDT'), ('AAVE', 'AAVE'), ('MLN', 'MLN'), ('LTC', 'LTC'), ('BTC', 'BTC'), ('MATIC', 'MATIC'), ('FARM', 'FARM'), ('MANA', 'MANA'), ('ALGO', 'ALGO'), ('STORJ', 'STORJ'), ('GRT', 'GRT'), ('NKN', 'NKN'), ('BNT', 'BNT'), ('KEEP', 'KEEP'), ('RLY', 'RLY'), ('WBTC', 'WBTC'), ('UNI', 'UNI'), ('CTSI', 'CTSI'), ('CHZ', 'CHZ'), ('ETH', 'ETH'), ('BAND', 'BAND'), ('XLM', 'XLM'), ('REP', 'REP'), ('ICP', 'ICP'), ('LRC', 'LRC'), ('SOL', 'SOL'), ('REN', 'REN'), ('NU', 'NU'), ('FORTH', 'FORTH'), ('ACH', 'ACH'), ('CLV', 'CLV'), ('RLC', 'RLC'), ('BOND', 'BOND'), ('RAI', 'RAI'), ('UMA', 'UMA'), ('OMG', 'OMG'), ('EOS', 'EOS'), ('ETC', 'ETC'), ('LPT', 'LPT'), ('FIL', 'FIL'), ('ZRX', 'ZRX'), ('SKL', 'SKL'), ('LINK', 'LINK'), ('CRV', 'CRV'), ('BAT', 'BAT'), ('MASK', 'MASK'), ('DASH', 'DASH')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('mo', 'Monthly'), ('wk', 'Weekly'), ('day', 'Daily'), ('bimo', 'BiMonthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('GBP', 'British Pounds'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='USD', max_length=3),
        ),
    ]
