# Generated by Django 3.2.5 on 2021-08-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0005_auto_20210807_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('BCH', 'BCH'), ('LRC', 'LRC'), ('XLM', 'XLM'), ('AMP', 'AMP'), ('NU', 'NU'), ('CGLD', 'CGLD'), ('COMP', 'COMP'), ('NKN', 'NKN'), ('ZRX', 'ZRX'), ('POLY', 'POLY'), ('QNT', 'QNT'), ('ATOM', 'ATOM'), ('ENJ', 'ENJ'), ('OXT', 'OXT'), ('TRB', 'TRB'), ('FET', 'FET'), ('DASH', 'DASH'), ('ALGO', 'ALGO'), ('FIL', 'FIL'), ('ADA', 'ADA'), ('OGN', 'OGN'), ('STORJ', 'STORJ'), ('WBTC', 'WBTC'), ('PAX', 'PAX'), ('BAL', 'BAL'), ('RAI', 'RAI'), ('SOL', 'SOL'), ('ICP', 'ICP'), ('BAT', 'BAT'), ('REP', 'REP'), ('FARM', 'FARM'), ('GTC', 'GTC'), ('FORTH', 'FORTH'), ('LTC', 'LTC'), ('MKR', 'MKR'), ('MATIC', 'MATIC'), ('ETC', 'ETC'), ('RLC', 'RLC'), ('BAND', 'BAND'), ('BTC', 'BTC'), ('MLN', 'MLN'), ('PLA', 'PLA'), ('ZEC', 'ZEC'), ('BNT', 'BNT'), ('XTZ', 'XTZ'), ('BOND', 'BOND'), ('DAI', 'DAI'), ('1INCH', '1INCH'), ('EOS', 'EOS'), ('AAVE', 'AAVE'), ('RLY', 'RLY'), ('GRT', 'GRT'), ('USDT', 'USDT'), ('ETH', 'ETH'), ('NMR', 'NMR'), ('REN', 'REN'), ('SNX', 'SNX'), ('MIR', 'MIR'), ('LPT', 'LPT'), ('MASK', 'MASK'), ('OMG', 'OMG'), ('ANKR', 'ANKR'), ('SKL', 'SKL'), ('CTSI', 'CTSI'), ('SUSHI', 'SUSHI'), ('LINK', 'LINK'), ('UNI', 'UNI'), ('ACH', 'ACH'), ('DOT', 'DOT'), ('CHZ', 'CHZ'), ('MANA', 'MANA'), ('KNC', 'KNC'), ('DOGE', 'DOGE'), ('CRV', 'CRV'), ('KEEP', 'KEEP'), ('CLV', 'CLV'), ('YFI', 'YFI'), ('UMA', 'UMA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('wk', 'Weekly'), ('bimo', 'BiMonthly'), ('day', 'Daily'), ('mo', 'Monthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('USD', 'US Dollars'), ('GBP', 'British Pounds')], default='USD', max_length=3),
        ),
    ]
