# Generated by Django 3.2.5 on 2021-08-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0006_auto_20210807_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('GRT', 'GRT'), ('POLY', 'POLY'), ('LRC', 'LRC'), ('EOS', 'EOS'), ('COMP', 'COMP'), ('UNI', 'UNI'), ('ACH', 'ACH'), ('ATOM', 'ATOM'), ('ENJ', 'ENJ'), ('MLN', 'MLN'), ('TRB', 'TRB'), ('USDT', 'USDT'), ('BAND', 'BAND'), ('CTSI', 'CTSI'), ('CGLD', 'CGLD'), ('RLC', 'RLC'), ('BAL', 'BAL'), ('XLM', 'XLM'), ('WBTC', 'WBTC'), ('MATIC', 'MATIC'), ('SKL', 'SKL'), ('SNX', 'SNX'), ('DOT', 'DOT'), ('LINK', 'LINK'), ('NU', 'NU'), ('ZEC', 'ZEC'), ('ICP', 'ICP'), ('OMG', 'OMG'), ('KEEP', 'KEEP'), ('ZRX', 'ZRX'), ('KNC', 'KNC'), ('RAI', 'RAI'), ('STORJ', 'STORJ'), ('NMR', 'NMR'), ('UMA', 'UMA'), ('FORTH', 'FORTH'), ('RLY', 'RLY'), ('XTZ', 'XTZ'), ('PAX', 'PAX'), ('1INCH', '1INCH'), ('ADA', 'ADA'), ('FARM', 'FARM'), ('REP', 'REP'), ('MASK', 'MASK'), ('CRV', 'CRV'), ('OGN', 'OGN'), ('ALGO', 'ALGO'), ('DASH', 'DASH'), ('GTC', 'GTC'), ('MKR', 'MKR'), ('QNT', 'QNT'), ('REN', 'REN'), ('BNT', 'BNT'), ('MIR', 'MIR'), ('SOL', 'SOL'), ('AMP', 'AMP'), ('DOGE', 'DOGE'), ('BOND', 'BOND'), ('NKN', 'NKN'), ('SUSHI', 'SUSHI'), ('ETH', 'ETH'), ('FET', 'FET'), ('BCH', 'BCH'), ('CHZ', 'CHZ'), ('LPT', 'LPT'), ('LTC', 'LTC'), ('AAVE', 'AAVE'), ('BTC', 'BTC'), ('OXT', 'OXT'), ('DAI', 'DAI'), ('ANKR', 'ANKR'), ('FIL', 'FIL'), ('MANA', 'MANA'), ('CLV', 'CLV'), ('YFI', 'YFI'), ('ETC', 'ETC'), ('BAT', 'BAT'), ('PLA', 'PLA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('wk', 'Weekly'), ('mo', 'Monthly'), ('day', 'Daily'), ('bimo', 'BiMonthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'Euros'), ('GBP', 'British Pounds')], default='USD', max_length=3),
        ),
    ]
