# Generated by Django 3.2.5 on 2021-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0008_auto_20210807_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('UNI', 'UNI'), ('ORN', 'ORN'), ('TRB', 'TRB'), ('LINK', 'LINK'), ('EOS', 'EOS'), ('FET', 'FET'), ('SOL', 'SOL'), ('STORJ', 'STORJ'), ('CLV', 'CLV'), ('DASH', 'DASH'), ('USDT', 'USDT'), ('LRC', 'LRC'), ('PAX', 'PAX'), ('ETC', 'ETC'), ('GTC', 'GTC'), ('OMG', 'OMG'), ('NKN', 'NKN'), ('MKR', 'MKR'), ('OXT', 'OXT'), ('UMA', 'UMA'), ('ZRX', 'ZRX'), ('ANKR', 'ANKR'), ('BNT', 'BNT'), ('WBTC', 'WBTC'), ('ETH', 'ETH'), ('NU', 'NU'), ('BAL', 'BAL'), ('BAT', 'BAT'), ('COMP', 'COMP'), ('REN', 'REN'), ('UST', 'UST'), ('LTC', 'LTC'), ('NMR', 'NMR'), ('BOND', 'BOND'), ('DOT', 'DOT'), ('MANA', 'MANA'), ('ZEC', 'ZEC'), ('KNC', 'KNC'), ('TRIBE', 'TRIBE'), ('OGN', 'OGN'), ('FIL', 'FIL'), ('RAI', 'RAI'), ('CHZ', 'CHZ'), ('XLM', 'XLM'), ('REP', 'REP'), ('AMP', 'AMP'), ('CGLD', 'CGLD'), ('1INCH', '1INCH'), ('RLC', 'RLC'), ('QNT', 'QNT'), ('RLY', 'RLY'), ('XTZ', 'XTZ'), ('MLN', 'MLN'), ('FORTH', 'FORTH'), ('SKL', 'SKL'), ('SUSHI', 'SUSHI'), ('ENJ', 'ENJ'), ('POLY', 'POLY'), ('MATIC', 'MATIC'), ('YFI', 'YFI'), ('LPT', 'LPT'), ('ACH', 'ACH'), ('ADA', 'ADA'), ('SNX', 'SNX'), ('QUICK', 'QUICK'), ('KEEP', 'KEEP'), ('PLA', 'PLA'), ('MIR', 'MIR'), ('DOGE', 'DOGE'), ('BCH', 'BCH'), ('ALGO', 'ALGO'), ('ICP', 'ICP'), ('DAI', 'DAI'), ('CRV', 'CRV'), ('MASK', 'MASK'), ('IOTX', 'IOTX'), ('CTSI', 'CTSI'), ('BTC', 'BTC'), ('AAVE', 'AAVE'), ('GRT', 'GRT'), ('BAND', 'BAND'), ('ATOM', 'ATOM'), ('FARM', 'FARM')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('bimo', 'BiMonthly'), ('day', 'Daily'), ('mo', 'Monthly'), ('wk', 'Weekly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='order_type',
            field=models.CharField(choices=[('limit', 'Limit'), ('market', 'Market')], default='market', max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('GBP', 'British Pounds'), ('EUR', 'Euros')], default='USD', max_length=3),
        ),
    ]
