# Generated by Django 3.2.5 on 2021-08-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0009_auto_20210811_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('FARM', 'FARM'), ('TRB', 'TRB'), ('MATIC', 'MATIC'), ('STORJ', 'STORJ'), ('BAT', 'BAT'), ('RAI', 'RAI'), ('REP', 'REP'), ('MANA', 'MANA'), ('WLUNA', 'WLUNA'), ('REN', 'REN'), ('ZEC', 'ZEC'), ('ACH', 'ACH'), ('USDT', 'USDT'), ('FORTH', 'FORTH'), ('YFI', 'YFI'), ('POLY', 'POLY'), ('BOND', 'BOND'), ('AMP', 'AMP'), ('SKL', 'SKL'), ('ENJ', 'ENJ'), ('UMA', 'UMA'), ('SUSHI', 'SUSHI'), ('ZRX', 'ZRX'), ('COMP', 'COMP'), ('WBTC', 'WBTC'), ('FET', 'FET'), ('OXT', 'OXT'), ('ADA', 'ADA'), ('CHZ', 'CHZ'), ('BAL', 'BAL'), ('CTSI', 'CTSI'), ('OMG', 'OMG'), ('GRT', 'GRT'), ('NKN', 'NKN'), ('KNC', 'KNC'), ('BTC', 'BTC'), ('AAVE', 'AAVE'), ('CGLD', 'CGLD'), ('SNX', 'SNX'), ('MASK', 'MASK'), ('LINK', 'LINK'), ('RLC', 'RLC'), ('ANKR', 'ANKR'), ('LRC', 'LRC'), ('NMR', 'NMR'), ('ALGO', 'ALGO'), ('1INCH', '1INCH'), ('UST', 'UST'), ('RLY', 'RLY'), ('LPT', 'LPT'), ('REQ', 'REQ'), ('NU', 'NU'), ('TRIBE', 'TRIBE'), ('DAI', 'DAI'), ('AXS', 'AXS'), ('UNI', 'UNI'), ('ETH', 'ETH'), ('IOTX', 'IOTX'), ('MLN', 'MLN'), ('BAND', 'BAND'), ('TRU', 'TRU'), ('PLA', 'PLA'), ('DOT', 'DOT'), ('KEEP', 'KEEP'), ('FIL', 'FIL'), ('MIR', 'MIR'), ('OGN', 'OGN'), ('LTC', 'LTC'), ('BCH', 'BCH'), ('CRV', 'CRV'), ('BNT', 'BNT'), ('XLM', 'XLM'), ('DASH', 'DASH'), ('ETC', 'ETC'), ('EOS', 'EOS'), ('DOGE', 'DOGE'), ('GTC', 'GTC'), ('QNT', 'QNT'), ('CLV', 'CLV'), ('MKR', 'MKR'), ('QUICK', 'QUICK'), ('PAX', 'PAX'), ('ATOM', 'ATOM'), ('ICP', 'ICP'), ('SOL', 'SOL'), ('XTZ', 'XTZ'), ('ORN', 'ORN')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('day', 'Daily'), ('mo', 'Monthly'), ('bimo', 'BiMonthly'), ('wk', 'Weekly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='order_type',
            field=models.CharField(choices=[('limit', 'Limit'), ('market', 'Market'), ('ladder', 'Ladder')], default='market', max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('GBP', 'British Pounds'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='USD', max_length=3),
        ),
    ]
