# Generated by Django 3.2.5 on 2021-08-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0011_auto_20210813_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('ANKR', 'ANKR'), ('MKR', 'MKR'), ('ADA', 'ADA'), ('XLM', 'XLM'), ('ACH', 'ACH'), ('BTC', 'BTC'), ('ATOM', 'ATOM'), ('BOND', 'BOND'), ('OMG', 'OMG'), ('MLN', 'MLN'), ('FET', 'FET'), ('RLC', 'RLC'), ('STORJ', 'STORJ'), ('AAVE', 'AAVE'), ('MIR', 'MIR'), ('COMP', 'COMP'), ('LTC', 'LTC'), ('REP', 'REP'), ('UNI', 'UNI'), ('AXS', 'AXS'), ('NMR', 'NMR'), ('DOT', 'DOT'), ('ETH', 'ETH'), ('BAL', 'BAL'), ('TRU', 'TRU'), ('QUICK', 'QUICK'), ('PLA', 'PLA'), ('ETC', 'ETC'), ('OGN', 'OGN'), ('WBTC', 'WBTC'), ('UST', 'UST'), ('IOTX', 'IOTX'), ('BNT', 'BNT'), ('BCH', 'BCH'), ('ORN', 'ORN'), ('PAX', 'PAX'), ('LRC', 'LRC'), ('LPT', 'LPT'), ('ZEC', 'ZEC'), ('AMP', 'AMP'), ('RAI', 'RAI'), ('SKL', 'SKL'), ('SNX', 'SNX'), ('ZRX', 'ZRX'), ('MATIC', 'MATIC'), ('XTZ', 'XTZ'), ('FARM', 'FARM'), ('ICP', 'ICP'), ('BAT', 'BAT'), ('SUSHI', 'SUSHI'), ('MASK', 'MASK'), ('GTC', 'GTC'), ('NU', 'NU'), ('LINK', 'LINK'), ('FIL', 'FIL'), ('DASH', 'DASH'), ('CHZ', 'CHZ'), ('USDT', 'USDT'), ('1INCH', '1INCH'), ('WLUNA', 'WLUNA'), ('KEEP', 'KEEP'), ('POLY', 'POLY'), ('CLV', 'CLV'), ('REQ', 'REQ'), ('ALGO', 'ALGO'), ('CGLD', 'CGLD'), ('DAI', 'DAI'), ('CRV', 'CRV'), ('DOGE', 'DOGE'), ('FORTH', 'FORTH'), ('KNC', 'KNC'), ('REN', 'REN'), ('SOL', 'SOL'), ('NKN', 'NKN'), ('GRT', 'GRT'), ('QNT', 'QNT'), ('TRB', 'TRB'), ('OXT', 'OXT'), ('RLY', 'RLY'), ('UMA', 'UMA'), ('BAND', 'BAND'), ('MANA', 'MANA'), ('EOS', 'EOS'), ('CTSI', 'CTSI'), ('YFI', 'YFI'), ('ENJ', 'ENJ'), ('TRIBE', 'TRIBE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('day', 'Daily'), ('wk', 'Weekly'), ('bimo', 'BiMonthly'), ('mo', 'Monthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='order_type',
            field=models.CharField(choices=[('limit', 'Limit'), ('market', 'Market'), ('ladder', 'Ladder')], default='market', max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'Euros'), ('GBP', 'British Pounds')], default='USD', max_length=3),
        ),
    ]
