# Generated by Django 3.2.5 on 2021-08-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0012_auto_20210813_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('ORN', 'ORN'), ('CTSI', 'CTSI'), ('LINK', 'LINK'), ('ZRX', 'ZRX'), ('XTZ', 'XTZ'), ('ATOM', 'ATOM'), ('FIL', 'FIL'), ('OXT', 'OXT'), ('BNT', 'BNT'), ('DOGE', 'DOGE'), ('REP', 'REP'), ('XLM', 'XLM'), ('RLC', 'RLC'), ('TRB', 'TRB'), ('AMP', 'AMP'), ('CRV', 'CRV'), ('LPT', 'LPT'), ('YFI', 'YFI'), ('DASH', 'DASH'), ('QNT', 'QNT'), ('PAX', 'PAX'), ('BOND', 'BOND'), ('ETH', 'ETH'), ('SKL', 'SKL'), ('REN', 'REN'), ('GTC', 'GTC'), ('BAND', 'BAND'), ('EOS', 'EOS'), ('AAVE', 'AAVE'), ('ENJ', 'ENJ'), ('USDT', 'USDT'), ('SOL', 'SOL'), ('PLA', 'PLA'), ('COTI', 'COTI'), ('STORJ', 'STORJ'), ('MATIC', 'MATIC'), ('COMP', 'COMP'), ('CGLD', 'CGLD'), ('NKN', 'NKN'), ('OGN', 'OGN'), ('MIR', 'MIR'), ('RAI', 'RAI'), ('ZEC', 'ZEC'), ('KNC', 'KNC'), ('REQ', 'REQ'), ('WLUNA', 'WLUNA'), ('FET', 'FET'), ('DOT', 'DOT'), ('IOTX', 'IOTX'), ('1INCH', '1INCH'), ('POLY', 'POLY'), ('MANA', 'MANA'), ('ANKR', 'ANKR'), ('MKR', 'MKR'), ('SUSHI', 'SUSHI'), ('FARM', 'FARM'), ('MLN', 'MLN'), ('AXS', 'AXS'), ('NMR', 'NMR'), ('UNI', 'UNI'), ('WBTC', 'WBTC'), ('ACH', 'ACH'), ('UMA', 'UMA'), ('DAI', 'DAI'), ('LRC', 'LRC'), ('LTC', 'LTC'), ('BAL', 'BAL'), ('ICP', 'ICP'), ('FORTH', 'FORTH'), ('GRT', 'GRT'), ('OMG', 'OMG'), ('UST', 'UST'), ('QUICK', 'QUICK'), ('ALGO', 'ALGO'), ('ADA', 'ADA'), ('BTC', 'BTC'), ('RLY', 'RLY'), ('BAT', 'BAT'), ('CHZ', 'CHZ'), ('SNX', 'SNX'), ('TRU', 'TRU'), ('MASK', 'MASK'), ('TRIBE', 'TRIBE'), ('KEEP', 'KEEP'), ('CLV', 'CLV'), ('BCH', 'BCH'), ('NU', 'NU'), ('ETC', 'ETC')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('wk', 'Weekly'), ('mo', 'Monthly'), ('day', 'Daily'), ('bimo', 'BiMonthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='order_type',
            field=models.CharField(choices=[('ladder', 'Ladder'), ('market', 'Market'), ('limit', 'Limit')], default='market', max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('GBP', 'British Pounds'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='USD', max_length=3),
        ),
    ]
