# Generated by Django 3.2.5 on 2021-09-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0013_auto_20210829_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('FET', 'FET'), ('LTC', 'LTC'), ('ANKR', 'ANKR'), ('BTC', 'BTC'), ('QUICK', 'QUICK'), ('USDT', 'USDT'), ('RLC', 'RLC'), ('SKL', 'SKL'), ('ENJ', 'ENJ'), ('LINK', 'LINK'), ('MATIC', 'MATIC'), ('ACH', 'ACH'), ('PLA', 'PLA'), ('KNC', 'KNC'), ('REQ', 'REQ'), ('MKR', 'MKR'), ('ETC', 'ETC'), ('ATOM', 'ATOM'), ('LRC', 'LRC'), ('SUSHI', 'SUSHI'), ('OXT', 'OXT'), ('MANA', 'MANA'), ('MIR', 'MIR'), ('ZRX', 'ZRX'), ('ETH', 'ETH'), ('CGLD', 'CGLD'), ('ZEC', 'ZEC'), ('SNX', 'SNX'), ('YFI', 'YFI'), ('GRT', 'GRT'), ('SOL', 'SOL'), ('FARM', 'FARM'), ('WLUNA', 'WLUNA'), ('BCH', 'BCH'), ('RLY', 'RLY'), ('ICP', 'ICP'), ('REN', 'REN'), ('CLV', 'CLV'), ('AMP', 'AMP'), ('FIL', 'FIL'), ('TRU', 'TRU'), ('CRV', 'CRV'), ('TRB', 'TRB'), ('BOND', 'BOND'), ('1INCH', '1INCH'), ('DDX', 'DDX'), ('XLM', 'XLM'), ('DASH', 'DASH'), ('YFII', 'YFII'), ('GTC', 'GTC'), ('UNI', 'UNI'), ('DAI', 'DAI'), ('POLY', 'POLY'), ('ALGO', 'ALGO'), ('BAT', 'BAT'), ('CHZ', 'CHZ'), ('EOS', 'EOS'), ('FORTH', 'FORTH'), ('AAVE', 'AAVE'), ('RAI', 'RAI'), ('DOGE', 'DOGE'), ('OGN', 'OGN'), ('ORN', 'ORN'), ('KEEP', 'KEEP'), ('NU', 'NU'), ('ADA', 'ADA'), ('RAD', 'RAD'), ('CTSI', 'CTSI'), ('COTI', 'COTI'), ('NKN', 'NKN'), ('REP', 'REP'), ('UST', 'UST'), ('WBTC', 'WBTC'), ('IOTX', 'IOTX'), ('COMP', 'COMP'), ('LPT', 'LPT'), ('STORJ', 'STORJ'), ('BAND', 'BAND'), ('TRIBE', 'TRIBE'), ('OMG', 'OMG'), ('BNT', 'BNT'), ('QNT', 'QNT'), ('BAL', 'BAL'), ('XTZ', 'XTZ'), ('AXS', 'AXS'), ('MLN', 'MLN'), ('DOT', 'DOT'), ('UMA', 'UMA'), ('MASK', 'MASK'), ('NMR', 'NMR'), ('PAX', 'PAX')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('day', 'Daily'), ('wk', 'Weekly'), ('mo', 'Monthly'), ('bimo', 'BiMonthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='order_type',
            field=models.CharField(choices=[('ladder', 'Ladder'), ('limit', 'Limit'), ('market', 'Market')], default='market', max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('GBP', 'British Pounds'), ('EUR', 'Euros')], default='USD', max_length=3),
        ),
    ]
