# Generated by Django 3.2.5 on 2021-09-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0014_auto_20210906_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('COTI', 'COTI'), ('UMA', 'UMA'), ('TRU', 'TRU'), ('YFII', 'YFII'), ('NU', 'NU'), ('NKN', 'NKN'), ('RLY', 'RLY'), ('CTSI', 'CTSI'), ('NMR', 'NMR'), ('ICP', 'ICP'), ('ALGO', 'ALGO'), ('ATOM', 'ATOM'), ('QNT', 'QNT'), ('RAI', 'RAI'), ('MLN', 'MLN'), ('ZEC', 'ZEC'), ('UST', 'UST'), ('LINK', 'LINK'), ('DASH', 'DASH'), ('POLY', 'POLY'), ('BCH', 'BCH'), ('SNX', 'SNX'), ('STORJ', 'STORJ'), ('YFI', 'YFI'), ('REQ', 'REQ'), ('MASK', 'MASK'), ('FET', 'FET'), ('FORTH', 'FORTH'), ('USDT', 'USDT'), ('ANKR', 'ANKR'), ('RLC', 'RLC'), ('1INCH', '1INCH'), ('DDX', 'DDX'), ('BAL', 'BAL'), ('MATIC', 'MATIC'), ('BAT', 'BAT'), ('BOND', 'BOND'), ('AMP', 'AMP'), ('FARM', 'FARM'), ('OXT', 'OXT'), ('KEEP', 'KEEP'), ('BNT', 'BNT'), ('BTC', 'BTC'), ('OMG', 'OMG'), ('ORN', 'ORN'), ('UNI', 'UNI'), ('EOS', 'EOS'), ('WLUNA', 'WLUNA'), ('CLV', 'CLV'), ('LRC', 'LRC'), ('COMP', 'COMP'), ('TRB', 'TRB'), ('CRV', 'CRV'), ('MIR', 'MIR'), ('IOTX', 'IOTX'), ('LTC', 'LTC'), ('ACH', 'ACH'), ('MKR', 'MKR'), ('MANA', 'MANA'), ('DAI', 'DAI'), ('QUICK', 'QUICK'), ('LPT', 'LPT'), ('BAND', 'BAND'), ('ETH', 'ETH'), ('ADA', 'ADA'), ('PAX', 'PAX'), ('SOL', 'SOL'), ('AAVE', 'AAVE'), ('GTC', 'GTC'), ('XTZ', 'XTZ'), ('GRT', 'GRT'), ('AXS', 'AXS'), ('FIL', 'FIL'), ('DOGE', 'DOGE'), ('CHZ', 'CHZ'), ('ZRX', 'ZRX'), ('SUSHI', 'SUSHI'), ('KNC', 'KNC'), ('ENJ', 'ENJ'), ('ETC', 'ETC'), ('XLM', 'XLM'), ('RAD', 'RAD'), ('WBTC', 'WBTC'), ('REP', 'REP'), ('REN', 'REN'), ('OGN', 'OGN'), ('CGLD', 'CGLD'), ('PLA', 'PLA'), ('DOT', 'DOT'), ('TRIBE', 'TRIBE'), ('SKL', 'SKL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('bimo', 'BiMonthly'), ('day', 'Daily'), ('mo', 'Monthly'), ('wk', 'Weekly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='order_type',
            field=models.CharField(choices=[('limit', 'Limit'), ('ladder', 'Ladder'), ('market', 'Market')], default='market', max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('USD', 'US Dollars'), ('GBP', 'British Pounds')], default='USD', max_length=3),
        ),
    ]
