# Generated by Django 3.2.9 on 2022-01-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0015_auto_20210907_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('API3', 'API3'), ('OXT', 'OXT'), ('COMP', 'COMP'), ('UST', 'UST'), ('DAI', 'DAI'), ('BAND', 'BAND'), ('NMR', 'NMR'), ('FIL', 'FIL'), ('ANKR', 'ANKR'), ('POLS', 'POLS'), ('ADA', 'ADA'), ('XYO', 'XYO'), ('POWR', 'POWR'), ('GTC', 'GTC'), ('DOT', 'DOT'), ('LINK', 'LINK'), ('MKR', 'MKR'), ('CGLD', 'CGLD'), ('MDT', 'MDT'), ('NKN', 'NKN'), ('XLM', 'XLM'), ('ZEN', 'ZEN'), ('1INCH', '1INCH'), ('DESO', 'DESO'), ('REP', 'REP'), ('UNI', 'UNI'), ('LRC', 'LRC'), ('KNC', 'KNC'), ('BNT', 'BNT'), ('BOND', 'BOND'), ('MLN', 'MLN'), ('CTSI', 'CTSI'), ('SUSHI', 'SUSHI'), ('EOS', 'EOS'), ('MIR', 'MIR'), ('SKL', 'SKL'), ('RBN', 'RBN'), ('DNT', 'DNT'), ('GRT', 'GRT'), ('XTZ', 'XTZ'), ('POLY', 'POLY'), ('MATIC', 'MATIC'), ('GALA', 'GALA'), ('USDT', 'USDT'), ('CHZ', 'CHZ'), ('ACH', 'ACH'), ('ARPA', 'ARPA'), ('ICP', 'ICP'), ('MANA', 'MANA'), ('MASK', 'MASK'), ('FET', 'FET'), ('KEEP', 'KEEP'), ('PERP', 'PERP'), ('LOOM', 'LOOM'), ('WBTC', 'WBTC'), ('TRIBE', 'TRIBE'), ('SNX', 'SNX'), ('CVC', 'CVC'), ('LTC', 'LTC'), ('FOX', 'FOX'), ('TRU', 'TRU'), ('AMP', 'AMP'), ('RLY', 'RLY'), ('QUICK', 'QUICK'), ('BADGER', 'BADGER'), ('ENJ', 'ENJ'), ('GYEN', 'GYEN'), ('SHIB', 'SHIB'), ('MUSD', 'MUSD'), ('SUPER', 'SUPER'), ('SPELL', 'SPELL'), ('RLC', 'RLC'), ('BTRST', 'BTRST'), ('YFII', 'YFII'), ('CLV', 'CLV'), ('IMX', 'IMX'), ('RARI', 'RARI'), ('REN', 'REN'), ('ZEC', 'ZEC'), ('RAI', 'RAI'), ('TRB', 'TRB'), ('CRO', 'CRO'), ('AGLD', 'AGLD'), ('AVAX', 'AVAX'), ('QNT', 'QNT'), ('BAL', 'BAL'), ('GFI', 'GFI'), ('FARM', 'FARM'), ('CRV', 'CRV'), ('WLUNA', 'WLUNA'), ('AAVE', 'AAVE'), ('IDEX', 'IDEX'), ('LCX', 'LCX'), ('ALGO', 'ALGO'), ('YFI', 'YFI'), ('NU', 'NU'), ('TBTC', 'TBTC'), ('WCFG', 'WCFG'), ('ENS', 'ENS'), ('PLA', 'PLA'), ('FORTH', 'FORTH'), ('LPT', 'LPT'), ('REQ', 'REQ'), ('ZRX', 'ZRX'), ('GODS', 'GODS'), ('BAT', 'BAT'), ('COVAL', 'COVAL'), ('DOGE', 'DOGE'), ('STORJ', 'STORJ'), ('DDX', 'DDX'), ('DASH', 'DASH'), ('BTC', 'BTC'), ('ETH', 'ETH'), ('SUKU', 'SUKU'), ('BCH', 'BCH'), ('JASMY', 'JASMY'), ('COTI', 'COTI'), ('AXS', 'AXS'), ('BICO', 'BICO'), ('PAX', 'PAX'), ('ALCX', 'ALCX'), ('MCO2', 'MCO2'), ('VGX', 'VGX'), ('RGT', 'RGT'), ('BLZ', 'BLZ'), ('ATOM', 'ATOM'), ('OMG', 'OMG'), ('IOTX', 'IOTX'), ('UMA', 'UMA'), ('FX', 'FX'), ('AUCTION', 'AUCTION'), ('RAD', 'RAD'), ('ASM', 'ASM'), ('KRL', 'KRL'), ('ETC', 'ETC'), ('OGN', 'OGN'), ('ORN', 'ORN'), ('SOL', 'SOL'), ('TRAC', 'TRAC')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('day', 'Daily'), ('wk', 'Weekly'), ('mo', 'Monthly'), ('bimo', 'BiMonthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('GBP', 'British Pounds'), ('EUR', 'Euros'), ('USD', 'US Dollars')], default='USD', max_length=3),
        ),
    ]
