# Generated by Django 3.2.9 on 2022-01-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0017_auto_20220115_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('ALCX', 'ALCX'), ('MUSD', 'MUSD'), ('ETH', 'ETH'), ('LPT', 'LPT'), ('POLY', 'POLY'), ('ICP', 'ICP'), ('YFI', 'YFI'), ('CGLD', 'CGLD'), ('STORJ', 'STORJ'), ('QUICK', 'QUICK'), ('XTZ', 'XTZ'), ('COMP', 'COMP'), ('DOGE', 'DOGE'), ('RARI', 'RARI'), ('BCH', 'BCH'), ('RLY', 'RLY'), ('LQTY', 'LQTY'), ('BLZ', 'BLZ'), ('GTC', 'GTC'), ('SOL', 'SOL'), ('BAND', 'BAND'), ('SUSHI', 'SUSHI'), ('PAX', 'PAX'), ('CLV', 'CLV'), ('UNI', 'UNI'), ('MLN', 'MLN'), ('ENJ', 'ENJ'), ('IOTX', 'IOTX'), ('REQ', 'REQ'), ('MATIC', 'MATIC'), ('SUKU', 'SUKU'), ('ANKR', 'ANKR'), ('LRC', 'LRC'), ('QNT', 'QNT'), ('1INCH', '1INCH'), ('IMX', 'IMX'), ('GALA', 'GALA'), ('MDT', 'MDT'), ('AXS', 'AXS'), ('GRT', 'GRT'), ('OXT', 'OXT'), ('MCO2', 'MCO2'), ('NU', 'NU'), ('WBTC', 'WBTC'), ('ZEC', 'ZEC'), ('FX', 'FX'), ('FORTH', 'FORTH'), ('BAT', 'BAT'), ('GFI', 'GFI'), ('ORN', 'ORN'), ('VGX', 'VGX'), ('RLC', 'RLC'), ('ALGO', 'ALGO'), ('BTRST', 'BTRST'), ('FARM', 'FARM'), ('CHZ', 'CHZ'), ('COTI', 'COTI'), ('BTC', 'BTC'), ('CRV', 'CRV'), ('UMA', 'UMA'), ('JASMY', 'JASMY'), ('USDT', 'USDT'), ('PRO', 'PRO'), ('MKR', 'MKR'), ('DNT', 'DNT'), ('WLUNA', 'WLUNA'), ('NCT', 'NCT'), ('AGLD', 'AGLD'), ('LINK', 'LINK'), ('KRL', 'KRL'), ('XLM', 'XLM'), ('ZRX', 'ZRX'), ('FOX', 'FOX'), ('COVAL', 'COVAL'), ('PLA', 'PLA'), ('SHIB', 'SHIB'), ('POWR', 'POWR'), ('AVAX', 'AVAX'), ('FET', 'FET'), ('POLS', 'POLS'), ('SUPER', 'SUPER'), ('LTC', 'LTC'), ('OMG', 'OMG'), ('ASM', 'ASM'), ('BOND', 'BOND'), ('FIL', 'FIL'), ('OGN', 'OGN'), ('SNX', 'SNX'), ('UST', 'UST'), ('BADGER', 'BADGER'), ('DESO', 'DESO'), ('DOT', 'DOT'), ('BICO', 'BICO'), ('CTSI', 'CTSI'), ('TBTC', 'TBTC'), ('ATOM', 'ATOM'), ('NMR', 'NMR'), ('MIR', 'MIR'), ('MASK', 'MASK'), ('NKN', 'NKN'), ('TRU', 'TRU'), ('TRB', 'TRB'), ('IDEX', 'IDEX'), ('YFII', 'YFII'), ('GODS', 'GODS'), ('DAI', 'DAI'), ('TRAC', 'TRAC'), ('ADA', 'ADA'), ('GYEN', 'GYEN'), ('RGT', 'RGT'), ('WCFG', 'WCFG'), ('RAI', 'RAI'), ('AUCTION', 'AUCTION'), ('EOS', 'EOS'), ('ETC', 'ETC'), ('DASH', 'DASH'), ('ACH', 'ACH'), ('BAL', 'BAL'), ('LOOM', 'LOOM'), ('REP', 'REP'), ('SPELL', 'SPELL'), ('KNC', 'KNC'), ('RAD', 'RAD'), ('CRO', 'CRO'), ('INV', 'INV'), ('LCX', 'LCX'), ('REN', 'REN'), ('MANA', 'MANA'), ('CVC', 'CVC'), ('ZEN', 'ZEN'), ('PERP', 'PERP'), ('AAVE', 'AAVE'), ('API3', 'API3'), ('BNT', 'BNT'), ('TRIBE', 'TRIBE'), ('RBN', 'RBN'), ('KEEP', 'KEEP'), ('ARPA', 'ARPA'), ('DDX', 'DDX'), ('XYO', 'XYO'), ('AMP', 'AMP'), ('ENS', 'ENS'), ('SKL', 'SKL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('day', 'Daily'), ('bimo', 'BiMonthly'), ('wk', 'Weekly'), ('mo', 'Monthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='order_type',
            field=models.CharField(choices=[('ladder', 'Ladder'), ('limit', 'Limit'), ('market', 'Market')], default='market', max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'British Pounds'), ('USD', 'US Dollars')], default='USD', max_length=10),
        ),
    ]
