# Generated by Django 3.2.9 on 2022-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCAstrategies', '0018_auto_20220117_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='API_key',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='keys',
            name='API_secret',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='crypto_product',
            field=models.CharField(choices=[('BCH', 'BCH'), ('MLN', 'MLN'), ('QNT', 'QNT'), ('CGLD', 'CGLD'), ('MATIC', 'MATIC'), ('KRL', 'KRL'), ('DESO', 'DESO'), ('IDEX', 'IDEX'), ('BAND', 'BAND'), ('NKN', 'NKN'), ('XLM', 'XLM'), ('CLV', 'CLV'), ('DNT', 'DNT'), ('KNC', 'KNC'), ('ATOM', 'ATOM'), ('OGN', 'OGN'), ('SNX', 'SNX'), ('RLY', 'RLY'), ('XTZ', 'XTZ'), ('PRO', 'PRO'), ('AXS', 'AXS'), ('WBTC', 'WBTC'), ('PAX', 'PAX'), ('TBTC', 'TBTC'), ('SHIB', 'SHIB'), ('ZRX', 'ZRX'), ('GTC', 'GTC'), ('AVAX', 'AVAX'), ('WCFG', 'WCFG'), ('QUICK', 'QUICK'), ('SKL', 'SKL'), ('GALA', 'GALA'), ('MKR', 'MKR'), ('XYO', 'XYO'), ('LCX', 'LCX'), ('MASK', 'MASK'), ('DOGE', 'DOGE'), ('REQ', 'REQ'), ('ENJ', 'ENJ'), ('RGT', 'RGT'), ('LTC', 'LTC'), ('EOS', 'EOS'), ('OMG', 'OMG'), ('ORN', 'ORN'), ('NMR', 'NMR'), ('RAI', 'RAI'), ('SUSHI', 'SUSHI'), ('CRV', 'CRV'), ('SUKU', 'SUKU'), ('IMX', 'IMX'), ('TRB', 'TRB'), ('COTI', 'COTI'), ('ZEC', 'ZEC'), ('FX', 'FX'), ('1INCH', '1INCH'), ('STORJ', 'STORJ'), ('DAI', 'DAI'), ('TRAC', 'TRAC'), ('DOT', 'DOT'), ('WLUNA', 'WLUNA'), ('DASH', 'DASH'), ('ACH', 'ACH'), ('ICP', 'ICP'), ('PLA', 'PLA'), ('KEEP', 'KEEP'), ('CVC', 'CVC'), ('LPT', 'LPT'), ('RBN', 'RBN'), ('AUCTION', 'AUCTION'), ('ETC', 'ETC'), ('JASMY', 'JASMY'), ('UMA', 'UMA'), ('LQTY', 'LQTY'), ('POWR', 'POWR'), ('REN', 'REN'), ('ARPA', 'ARPA'), ('AAVE', 'AAVE'), ('RLC', 'RLC'), ('COMP', 'COMP'), ('POLS', 'POLS'), ('FARM', 'FARM'), ('PERP', 'PERP'), ('VGX', 'VGX'), ('LRC', 'LRC'), ('INV', 'INV'), ('ALGO', 'ALGO'), ('GRT', 'GRT'), ('MIR', 'MIR'), ('UST', 'UST'), ('BTRST', 'BTRST'), ('ANKR', 'ANKR'), ('NU', 'NU'), ('OXT', 'OXT'), ('FIL', 'FIL'), ('POLY', 'POLY'), ('BAT', 'BAT'), ('FET', 'FET'), ('GFI', 'GFI'), ('RAD', 'RAD'), ('BTC', 'BTC'), ('BNT', 'BNT'), ('ASM', 'ASM'), ('RARI', 'RARI'), ('GODS', 'GODS'), ('AMP', 'AMP'), ('ZEN', 'ZEN'), ('MUSD', 'MUSD'), ('SPELL', 'SPELL'), ('BLZ', 'BLZ'), ('UNI', 'UNI'), ('FOX', 'FOX'), ('CTSI', 'CTSI'), ('ENS', 'ENS'), ('BADGER', 'BADGER'), ('YFII', 'YFII'), ('FORTH', 'FORTH'), ('TRIBE', 'TRIBE'), ('IOTX', 'IOTX'), ('LOOM', 'LOOM'), ('API3', 'API3'), ('ADA', 'ADA'), ('SOL', 'SOL'), ('SUPER', 'SUPER'), ('ETH', 'ETH'), ('CHZ', 'CHZ'), ('AGLD', 'AGLD'), ('LINK', 'LINK'), ('YFI', 'YFI'), ('COVAL', 'COVAL'), ('CRO', 'CRO'), ('REP', 'REP'), ('MCO2', 'MCO2'), ('NCT', 'NCT'), ('MDT', 'MDT'), ('MANA', 'MANA'), ('BOND', 'BOND'), ('BICO', 'BICO'), ('TRU', 'TRU'), ('ALCX', 'ALCX'), ('DDX', 'DDX'), ('BAL', 'BAL'), ('GYEN', 'GYEN'), ('USDT', 'USDT')], max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='execution_frequency',
            field=models.CharField(choices=[('day', 'Daily'), ('wk', 'Weekly'), ('mo', 'Monthly'), ('bimo', 'BiMonthly')], default='day', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='order_type',
            field=models.CharField(choices=[('limit', 'Limit'), ('ladder', 'Ladder'), ('market', 'Market')], default='market', max_length=30),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='quote_currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('EUR', 'Euros'), ('GBP', 'British Pounds')], default='USD', max_length=10),
        ),
    ]
